### ISSUE TITLE
这个错误是要去seg上面去安装这个吗？

### ISSUE THREAD

**Issue by zwj19991999** [greenplum-db/geospatial#13]
psql -d BDLDB -f ${GPHOME}/share/postgresql/contrib/postgis-2.1/postgis.sql
postgis.sql:95: ERROR:  could not access file "$libdir/postgis-2.1": No such file or directory

**Comment by kaknikhil** [comment]
@zwj19991999 
thank you for reporting the issue. Did you follow the instructions from the readme for compiling ?
It looks like that the geospatial .so file was not installed. Did your compilation go through and did you run make install?

**Comment by HogwartsRico** [comment]
when i start a  new issue ,i didn't see your issur, it looks like you have  the same problem , finally i solved 
you can see here https://github.com/greenplum-db/geospatial/issues/14 

我在提issue的时候并没有看到你提的问题，不过后来我解决了，你可以参照我的解决方法  
https://github.com/greenplum-db/geospatial/issues/14

**Comment by kaknikhil** [comment]
Closing this issue. Added instructions in readme see https://github.com/greenplum-db/geospatial/pull/15
