### ISSUE TITLE
regress error on 'SPI_palloc called while not connected to SPI (spi.c:1147)'

### ISSUE THREAD

**Issue by longforrich** [greenplum-db/geospatial#50]
e.g sfcgal/tickets
in function getSRSbySRID at geospatial/postgis/build/postgis-2.5.4/postgis/lwgeom_export.c
I saw
```
    if (getSRSbySRIDbyRule(srid, short_crs, query) != NULL) {
        size = strlen(query) + 1;
        srscopy = SPI_palloc(size);
        memcpy(srscopy, query, size);
        return srscopy;
    }

    if (SPI_OK_CONNECT != SPI_connect ())
    {
        elog(NOTICE, "getSRSbySRID: could not connect to SPI manager");
        SPI_finish();
        return NULL;
    }
```
The key point is doing 'SPI_palloc' before 'SPI_connect' will raise an error 'SPI_palloc called while not connected to SPI'.
So I moved 'SPI_connect'  before 'getSRSbySRIDbyRule' and add SPI_finish() before return srscopy, it can work.

**Comment by longforrich** [comment]
GPDB is 7.0.0-beta.2
geospatial branch is ok-gp7 & postgis is 2.5.4

**Comment by orhankislal** [comment]
PostGIS 3.3.2 on GP7 fixes this issue.
